ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_topU3l_MwScheme_UFO'
     $ //'-massless_2t'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_385 = ', GC_385
      WRITE(*,2) 'GC_386 = ', GC_386
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_7 = ', GC_7
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_202 = ', GC_202
      WRITE(*,2) 'GC_203 = ', GC_203
      WRITE(*,2) 'GC_263 = ', GC_263
      WRITE(*,2) 'GC_264 = ', GC_264
      WRITE(*,2) 'GC_351 = ', GC_351
      WRITE(*,2) 'GC_352 = ', GC_352
      WRITE(*,2) 'GC_357 = ', GC_357
      WRITE(*,2) 'GC_358 = ', GC_358
      WRITE(*,2) 'GC_365 = ', GC_365
      WRITE(*,2) 'GC_367 = ', GC_367
      WRITE(*,2) 'GC_368 = ', GC_368
      WRITE(*,2) 'GC_369 = ', GC_369
      WRITE(*,2) 'GC_441 = ', GC_441
      WRITE(*,2) 'GC_442 = ', GC_442
      WRITE(*,2) 'GC_451 = ', GC_451
      WRITE(*,2) 'GC_452 = ', GC_452
      WRITE(*,2) 'GC_504 = ', GC_504
      WRITE(*,2) 'GC_506 = ', GC_506
      WRITE(*,2) 'GC_524 = ', GC_524
