ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MH1,MDL_MT,MDL_MW,MDL_MZ,MDL_MZ1,MDL_MB
     $ ,MDL_MW1,MDL_MH,MDL_MT1

      COMMON/MASSES/ MDL_MH1,MDL_MT,MDL_MW,MDL_MZ,MDL_MZ1,MDL_MB
     $ ,MDL_MW1,MDL_MH,MDL_MT1


      DOUBLE PRECISION MDL_WH1,MDL_WH,MDL_WW,MDL_WT,MDL_WZ,MDL_WW1
     $ ,MDL_WT1,MDL_WZ1

      COMMON/WIDTHS/ MDL_WH1,MDL_WH,MDL_WW,MDL_WT,MDL_WZ,MDL_WW1
     $ ,MDL_WT1,MDL_WZ1


      DOUBLE COMPLEX GC_385, GC_386, GC_6, GC_7, GC_8, GC_1, GC_2,
     $  GC_202, GC_203, GC_263, GC_264, GC_351, GC_352, GC_357, GC_358
     $ , GC_365, GC_367, GC_368, GC_369, GC_441, GC_442, GC_451,
     $  GC_452, GC_504, GC_506, GC_524

      COMMON/COUPLINGS/ GC_385, GC_386, GC_6, GC_7, GC_8, GC_1, GC_2,
     $  GC_202, GC_203, GC_263, GC_264, GC_351, GC_352, GC_357, GC_358
     $ , GC_365, GC_367, GC_368, GC_369, GC_441, GC_442, GC_451,
     $  GC_452, GC_504, GC_506, GC_524

